spring:
  application:
    name: GatewayMS
  cloud:
    consul:
      host: localhost
      config:
        enabled: false
  gateway:
    discovery:
      locator:
        enabled: true
    routes:
      - id: UserMS
        uri: http://localhost:4000
        predicates:
          - path=/users/**
      - id: TweetMS
        uri: http://localhost:5000
        predicates:
          - path=/tweets/**
server:
  port: 8000
jwt:
  secret: ${JWT_SECRET:mySecretKeyForJwtTokenGeneration12345}